name: CI-CD

on: push

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    
    env:
      MLFLOW_TRACKING_USERNAME: saabiqcs
      # MLflow requires your token to be passed as the password
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      # DagsHub Python client requires this specific token variable
      DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1
      AWS_DEFAULT_REGION: ap-south-1

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
          cache: 'pip' 

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: DVC Pull (S3 remote)
        run: |
          dvc remote modify myremote --local access_key_id "${AWS_ACCESS_KEY_ID}"
          dvc remote modify myremote --local secret_access_key "${AWS_SECRET_ACCESS_KEY}"
          dvc pull -r myremote || echo "Some files are missing in DVC remote!"
          dvc checkout --force || echo "Some files may not have checked out properly!"

      - name: Test Model Registry
        run: |
          pytest tests/test_model_registry.py

      - name: Test Model Performance
        run: |
          pytest tests/test_model_perf.py

      - name: Promote Model
        if: success()
        run: |
          python scripts/promote_model_to_prod.py

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

  
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_REPOSITORY_URI }}
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Zip files for deployment
        if: success()
        run: |
          zip -r deployment.zip appspec.yml deploy/scripts/install_dependencies.sh deploy/scripts/start_docker.sh

      - name: Upload ZIP to S3
        if: success()
        run: |
          aws s3 cp deployment.zip s3://deliverytimepredictiondeploymentbysaabiq/deployment.zip

      - name: Deploy to AWS CodeDeploy
        if: success()
        run: |
          aws deploy create-deployment \
            --application-name delivery-time-predicition-app \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name delivery-time-prediction-grp \
            --s3-location bucket=deliverytimepredictiondeploymentbysaabiq,key=deployment.zip,bundleType=zip \
            --file-exists-behavior OVERWRITE \
            --region ap-south-1